### ISSUE TITLE
Bug Fixes and refinement based on feedback

### ISSUE THREAD

**Issue by Ndiritu** [microsoftgraph/msgraph-sdk-php#950]
Parent task tracking bug fixes, feedback & suggestions to improve v2.0:

## Bugs
- [x] https://github.com/microsoft/kiota/issues/1933
- [x] https://github.com/microsoftgraph/msgraph-sdk-php/issues/939
- [x] https://github.com/microsoftgraph/msgraph-sdk-php/issues/979
- [x] https://github.com/microsoftgraph/msgraph-beta-sdk-php/issues/71 (Beta SDK Generation issues)
- [x] https://github.com/microsoftgraph/msgraph-sdk-php/issues/1006
- [x] #854 - interim fix made. Awaiting further feedback from issue creators

## Enhancements
- [x] https://github.com/microsoftgraph/msgraph-sdk-php/issues/951
- [x] https://github.com/microsoft/kiota/issues/1856
- [x] https://github.com/microsoftgraph/msgraph-sdk-php/issues/952 - pattern agreed. Implementation to be done during PHP 8 support
